[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.tox
  | \.github
  | \.venv
  | dist
  | migrations
  | dj_ai
  | __pycache__
)/
'''

